### ISSUE TITLE
net/toxcore doesn't package

### ISSUE THREAD

**Issue by aSourceFish** [jasperla/openbsd-wip#76]
Hi! Your outdate net/toxcore doesn't currently package because of wrong WANTLIB (estdc++) and wrong PLIST (not existing files)
I tried to contact its maintainer, but he is silent.

**Comment by thfrwn** [comment]
Hi, sorry that nobody got back to you. This means that apparently nobody who works on OpenBSD-WIP has an interest in it at the moment.

However this is just a development repo. If you just want a functioning package for yourself, then just clone it, fix it, and keep it in your /usr/ports/mystuff or similar. If you think this might be of general interest, then you can fix the package, make sure it aligns with the openbsd porting guidelines, and then propose it with the ports@ mailing list.

Unless a ports developer from openbsd-wip steps up, I'm otherwise gonna close the issue.

**Comment by aSourceFish** [comment]
Hi!
Sorry for not responding (I didn't get notification).
I already have done both of that long time ago: https://marc.info/?l=openbsd-ports&m=151281050527056&w=2 https://github.com/aSourceFish/myports/tree/master/net

**Comment by aSourceFish** [comment]
I'll keep local copy of this port until I find a replacement or you merge/update it.
